### ISSUE TITLE
Fabric canvas  background colors change is not working as expected. 

### ISSUE THREAD

**Issue by khajaordant** [lyzerk/fabric-history#11]
If I add color Red, Black, Blue. 

then when calling .undo()  background is not going  Blue, Black, red. 

it is going Blue to White.   This is not expected while Undo.

**Comment by perryjsteward** [comment]
HI,  I'm also experiencing this issue with my project.

I have a series on controls where i edit an object i.e. change the color to red. when i peform .undo() the object is removed or oved to its previous position.

I have tried implementing your on/off history functions around my object modification functions but im not sure if this is correct.

**use case:** create an object and then use an object.set('fill', 'red') fabricjs function to set the objects new color and then peform an undo() to return to the previous color.
**expected outcome:** color changes to previous color
**actual outcome:** removes the object from canvas

**Comment by perryjsteward** [comment]
Hiya just a little update. I think my first explanation may be slightly wrong.

If i make more than 1 update to the object i.e. set the color from its original black to red to blue to green. the undo function works up to the color red and then will not revert back to the original color of black instead it removes the object as though that bit of its history didnt exist.

This is the same for any changes fill, fontstyles etc.

**Comment by lyzerk** [comment]
Hi everyone,

I just find a time to solve the issues. The fabricJS do not have an object:updated event. Therefore, after the changing a fill, font style, font weight, etc. You have to trigger an event manually.

For example,

```javascript
        function test() {
            const activeObjects = canvas.getActiveObjects();

            // remove objects
            if (activeObjects.length > 0) {
                for (var i = 0; i < activeObjects.length; i++) {
                    activeObjects[i].set('fill', 'purple')
                }
            }

            canvas.renderAll();
            canvas.trigger('object:modified');
        }
```

The event will save the state.

On the contrast, we can override the `set` method on fabric object and trigger that event but I wouldn't do that to a such a common function.

Thanks.
