### ISSUE TITLE
Fabric History Starting Point

### ISSUE THREAD

**Issue by perryjsteward** [lyzerk/fabric-history#12]
Hi,

When i create my canvas i add some default objects to the layout for the user to play around with. The fabric-history module takes these objects being added into its history and on undo will remove them.

I'm hoping there might be a way that i can define a starting point for fabric-history so that this does not happen.

**Type**: Question
**use case**: Define a starting point in Fabrics history
**Expected outcome**: when a user undo history it only goes back to the defined point in time

Cheers,
Perry

**Comment by lyzerk** [comment]
Hello,

You may use clearHistory function from the starting point. It will clear the undo/redo stacks and you will have the starting point that you want.

**Comment by perryjsteward** [comment]
amazing thank you!
