### ISSUE TITLE
Problems with custom classes & properties

### ISSUE THREAD

**Issue by perryjsteward** [lyzerk/fabric-history#14]
Heya,

I've created some custom classes with FabricJS and am coming across issues with undo/redo.

i THINK the problem is how im intitalising those custom classes rather than anything to do with this libraries implementation. Have you successfully got history working with custom classes?

Thanks,
Perry

**Comment by perryjsteward** [comment]
my main custom classes are groups as an FYI. but i also use Rect and IText

**Comment by lyzerk** [comment]
Hello,

I didn't try that. Do you have any example code that reproduce the problem ?

Thanks,
Alim

**Comment by perryjsteward** [comment]
I've managed to fix the issue with a bit of a work around.

The problem is if you simply create a custom class and put some extra new fields in there like color or size or whatever i.e.

`fabric.GaCanvas = fabric.util.createClass(fabric.Group, {
          size: 'large'
};)`

these custom properties dont get copied in the loadfromjson steps. So as well as creating the custom objects you need to extend some of their methods.

```
 fabric.GaCanvas.prototype.toObject = (function (toObject) {
            return function (propertiesToInclude) {
                propertiesToInclude = (propertiesToInclude || []).concat([
                    'id',
                    '_color',
                    '_fill',
                    '_radius',
                    '_dropShadow',
                    '_bold',
                    '_italic',
                    '_underline',
                    '_backgroundColor',
                    '_arrowPosition',
                    '_backgroundImage',
                    '_setBackgroundImage',
                    'selectable',
                    '_originalSize',
                    'lockMovementX',
                    'lockMovementY',
                    'hasControls',
                    'hasBorders',
                    'top',
                    'editable',
                    'dragBorderWidth',
                ]);
                return toObject.apply(this, [propertiesToInclude]);
            };
        })(fabric.GaCanvas.prototype.toObject);
```

**Comment by lyzerk** [comment]
Hi,

If I understand the problem correctly, you want to save state of the properties. In that case, you can use `canvas.extraProps` array and set that properties like `canvas.extraProps = ['customProp', '_bold', '_italic']` and `toDatalessJSON` will catch those properties for each object.

Thanks.

**Comment by perryjsteward** [comment]
thats amazing I will try this out, if it works itll reducxe a lot of custom code to create classes
