### ISSUE TITLE
Have you tried Patterns?

### ISSUE THREAD

**Issue by perryjsteward** [lyzerk/fabric-history#15]
Hiya, 

me again :) Im just wondering if you have tried using patterns with loadfromjson. I'm trying to include it in my project and having some issues with the object dissapearing from the canvas when i undeo then redo to reapply the pattern.

**Steps**
1. Add an object to canvas
2. set fill to a color
3. update object fill to a dynamic pattern
4. try undo
5. try redo

**Expected outcome**: pattern is reapplied to object
**Actual outcome**: object dissapears from canvas

this is my code to set fill with a pattern, i have implemented the function as a custom function of a group class i created. the area object is a Rect within the group.

```
 _setBackgroundImage: function (url) {
                canvas.offHistory();
                const area = this._objects.find((el) => el.id === 'canvas-area' );

                const self = this;

                fabric.Image.fromURL(url, function (img) {

                    if (area.width > area.height) {
                        img.scaleToWidth(area.width);
                    } else {
                        img.scaleToHeight(area.height);
                    }

                    var patternSourceCanvas = new fabric.StaticCanvas();
                    patternSourceCanvas.add(img);
                    patternSourceCanvas.renderAll();

                    patternSourceCanvas.setDimensions({
                        width: img.getScaledWidth(),
                        height: img.getScaledHeight(),
                    });
                    patternSourceCanvas.renderAll();

                    var pattern = new fabric.Pattern({
                        source: patternSourceCanvas.getElement(),
                        repeat: 'repeat',
                    });

                    area.set('fill', pattern);
                    self.set('_backgroundImage', url);
                    canvas.onHistory();
                    canvas.renderAll();
                });
            },
```

**Comment by perryjsteward** [comment]
For a bit more information I have noticed than if i print the group object after a redo in this instance the _objects array is empty where i should infact have my 2 objects i.e. the area object as seen in the code snippet

**Comment by lyzerk** [comment]
I think it is same problem as #11. After the canvas `renderAll` method you have to trigger an event to catch history.
