### ISSUE TITLE
How can i clear json data when using clearHistory function

### ISSUE THREAD

**Issue by stkrules2** [lyzerk/fabric-history#16]
i change my whole canvas dynamically
Now for every new canvas i use `clearHistory` function but the `json` file is not empty so when `undo` and `redo` is used on the new canvas it renders the previous canvas data so i want to clear `json`
i tried to modify your code but i am not that good so wasn't able to do it

Your library is nice though :)

**Comment by stkrules2** [comment]
basically what i want is to clear everything in clearHistory function which means all the history json

**Comment by lyzerk** [comment]
Hello,

```js
fabric.Canvas.prototype.clearHistory = function() {
  this.historyUndo = [];
  this.historyRedo = [];
  this.fire('history:clear');
}
```
`canvas.clearHistory();` is doing what you want I think. The stacks will be empty after call this function.

Thank you
