### ISSUE TITLE
Way to selectively turn off adding to history?

### ISSUE THREAD

**Issue by ttseng** [lyzerk/fabric-history#19]
Is there a way you would recommend for selectively toggling on and off saving changes to the history stack?

In particular, I want certain actions on fabric canvas to be ignored when undoing / redoing.

I thought I would be able to use `canvas.offHistory()` and `canvas.onHistory()` to disable saving state when adding selected objects, e.g.

```
    canvas.offHistory();
    canvas.add(obj);   
    
    canvas.renderAll();
    canvas.onHistory();
```

but this still fires `history:append`

**Comment by lyzerk** [comment]
Hello, could you test without call the canvas.onHistory() ? Because the onHistory may fire history:append.

Thanks,

**Comment by ttseng** [comment]
Thanks for your response!  

Yes - using `canvas.onHistory()` fires `history:append` - I'm trying to turn history back on for all other objects, though.

In other words - every time a user places an object on the canvas, I'm actually placing two objects – one that's visible to the user, and one that's only used for exporting from the canvas (in my case, for printing).  I always want the visible object to be added the history, but the hidden object shouldn't be so that the user doesn't have to hit the undo / redo button twice.

```
function addToCanvas(){
     // save the visible obj1 to history
     canvas.add(obj1)

     // ignore the hidden object obj2 from history
     canvas.offHistory();
     canvas.add(obj2);
     canvas.onHistory();
}
```

**Comment by lyzerk** [comment]
This is a very nice user case. I think we should consider disable history as object specific. What I mean, if we add such a flag 

`obj2.disableHistory = true` like. Then plugin should consider this object must removed from the history stack at all.

I think we need to develop such kind of a feature.

**Comment by lk77** [comment]
Hello,

i have the same kind of issue when calling setActiveObject method, i don't want another undo object beeing pushed into the stack, my solution is for now :

```
this.canvas.historyProcessing = true;
this.canvas.setActiveObject(textbox);
this.$nextTick(() => {
    this.canvas.historyProcessing = false;
})
```

i'm using the nextTick method from vuejs, but a setTimeout will work the same way i think.
