### ISSUE TITLE
Cannot undo added image

### ISSUE THREAD

**Issue by JamalAPI** [lyzerk/fabric-history#2]
I am adding base64 image to to canvas,which works fine on iOS, but the undo option operation causes an error:

(in (null);3) Unexpected identifier 'code'. Expected either a closing ']' or a ',' following an array element.

Any idea what the reason for this?

**Comment by JamalAPI** [comment]
It seems the canvas.loadFromJSON() does not like clipTo with a function call and chokes on:

fabric.Image.fromURL(myImg, function (oImg) {
      oImg.set({
        angle: 0,
        left: 140,
        top: 100,
        scaleX: 0.3,
        scaleY: 0.3,
        clipTo: roundedCorners.bind(oImg)
      });

So, the jSon string contained the following and canvas.loadFromJSON()  gave the error above.

"clipTo": "function roundedCorners() {\n [native code]\n}"

and failed!!

**Comment by lyzerk** [comment]
Hello,

I will look into it.

Thanks for the issue

**Comment by JamalAPI** [comment]
Actually, you may close this issue. It's a fabricjs issue as I discovered that the canvas.toJSON() was creating the following mangled **clipTo** property:

"clipTo": "function roundedCorners() {\n [native code]\n}"
**which should have been left alone as:**
"clipTo": "function roundedCorners().bind(img)

in the JSON string:

{
	"version": "3.4.0",
	"objects": [{
		"type": "image",
		"version": "3.4.0",
		"originX": "left",
		"originY": "top",
		"left": 62.22,
		"top": 134.86,
		"width": 826,
		"height": 620,
		"fill": "rgb(0,0,0)",
		"stroke": null,
		"strokeWidth": 0,
		"strokeDashArray": null,
		"strokeLineCap": "butt",
		"strokeDashOffset": 0,
		"strokeLineJoin": "miter",
		"strokeMiterLimit": 4,
		"scaleX": 0.3,
		"scaleY": 0.3,
		"angle": 0,
		"flipX": false,
		"flipY": false,
		"opacity": 1,
		"shadow": null,
		"visible": true,
		"clipTo": "function roundedCorners() {\n [native code]\n}",
		"backgroundColor": "",
		"fillRule": "nonzero",
		"paintFirst": "fill",
		"globalCompositeOperation": "source-over",
		"transformMatrix": null,
		"skewX": 0,
		"skewY": 0,
		"crossOrigin": "",
		"cropX": 0,
		"cropY": 0,
		"src": "data:image/jpeg;base64, For the sake of space I removed encoded base64 string",
		"filters": []
	}]
}

**BTW, great job on on your fabric-history class.**
