### ISSUE TITLE
New History Path

### ISSUE THREAD

**Issue by perryjsteward** [lyzerk/fabric-history#21]
Hiya,

I've noticed a history persistence issue with redo/undo. It seems that the history path is not cleared when you redo and start a new path. This is quite hard to explain so hopefully the steps to create helps make it clearer.

steps to recreate:
1. add text
2. change text color
3. change text size
4. undo x 3 so we are back at step 1
5. change font wieght
6. redo x 1

expected outcome: nothing happens
actual outcome: reverts state to step 2

**Comment by lyzerk** [comment]
Hey,

I think the problem here the chaning text color and size without history point. The fabricjs does not fire object:modified when that properties are changed. Therefore you have to call the history event by yourself. Reference to #11 

```javascript
canvas.trigger('object:modified');
```

Thanks !
