### ISSUE TITLE
Trigger history save on Text color change

### ISSUE THREAD

**Issue by anishjana** [lyzerk/fabric-history#22]
First of all Kudos for the awesome library.

So i have a template creator where I can add Text and change color, boldness, italic of the Text.
However When i undo, the previous color/boldness/italicised doe not appear. It goes back to the event before text was added.

On further check, Only the below events fire ;
```
object:added': this._historySaveAction,
      'object:removed': this._historySaveAction,
      'object:modified': this._historySaveAction,
      'object:skewing': this._historySaveAction, 
```

The object:modified does not fire on the inner properties modification of text .

**Comment by lyzerk** [comment]
Hey,

Fabricjs does not firing object:modified when that properties are changed. Therefore, you have to call the history point event by yourself. After any of the property is changed. You can call ;
```javascript
canvas.trigger('object:modified');
```
You can see #11 for such kind of the action.

Thanks !
