### ISSUE TITLE
Uncaught TypeError: canvas.undo is not a function

### ISSUE THREAD

**Issue by MethDamon** [lyzerk/fabric-history#27]
When importing the script using several different ways, I always get:

Uncaught TypeError: canvas.undo is not a function

Tried with fabric 3.4.0 like in the example in the readme and also with fabric 4.4.0

I copy pasted the example in the readme into a html file and it produces the same error

**Comment by hperezs** [comment]
I am encountering the same issue, any possible solutions?

**Comment by lyzerk** [comment]
Hi,

I found the problem and fixed it. The example code was using raw of GitHub file which does not work as it should. So, I replaced with a correct version of the plugin. 

I have updated the ReadMe file. Don't forget, the example code shouldn't be used like this. You should use NPM.

Thank you.
