### ISSUE TITLE
History doesn't work correctly

### ISSUE THREAD

**Issue by nandordudas** [lyzerk/fabric-history#3]
If `undo` or `redo` is called only one times more, the history will broke.

Reproduce steps:
- draw a line,
- push `Undo` button - first time,
- push `Undo` button - second time,
- history is gone.

Above steps same on redoing.

[Codepen example]

[Codepen example]: https://codepen.io/nandordudas/pen/vYBdeqo

**Comment by lyzerk** [comment]
`object:skewing` is triggered after draw a line. It was missing I have added on this commit https://github.com/lyzerk/fabric-history/commit/155a17d8100bf557907a0ab60b132ff56d773f12.
