### ISSUE TITLE
Create an ability to store custom properties

### ISSUE THREAD

**Issue by pokhrelashok** [lyzerk/fabric-history#31]
I have given some custom properties to my canvas object and i would like to store those in the history. Fabric JS accepts an array of  prop names while converting it to json. Is there a way we can specify them and store those as well when storing the history?

**Comment by vimlesh1975** [comment]
I am facing this same isuue.

**Comment by vimlesh1975** [comment]
canvas.extraProps = ['id', 'selectable']
Solves this problem. Thank you.
