### ISSUE TITLE
Does not work as expected

### ISSUE THREAD

**Issue by tomaslamacz** [lyzerk/fabric-history#4]
After I
**draw something, then UNDO it, draw something else, then again UNDO it,** 
I always get a wrong state.

**Comment by lyzerk** [comment]
Not enough information. Give more information about your environment and how does your code work. The plugin works perfectly.

**Comment by tomaslamacz** [comment]
Step 1: draw a vertical line:
![step1](https://user-images.githubusercontent.com/43873811/73636673-c2fa1800-4666-11ea-9142-e55a16ba68fe.png)
Step 2: press UNDO:
![step2](https://user-images.githubusercontent.com/43873811/73636698-d2796100-4666-11ea-89f0-46fa4d40f3d4.png)
Step 3: draw a horizontal line:
![step3](https://user-images.githubusercontent.com/43873811/73636724-dc02c900-4666-11ea-8490-da1993048457.png)
Step 4: press UNDO:
![step4](https://user-images.githubusercontent.com/43873811/73636740-e6bd5e00-4666-11ea-9577-b5e684b94f68.png)
In step 4, I get the vertical line instead of a blank canvas, which I should get  - so this is wrong.

**Comment by lyzerk** [comment]
Did you stop drawing after draw second line ? Fabricjs does not working like that. You have to stop drawing for getting the real history. Therefore, if you stop drawing (disable drawing mode, or add rectangle, or click different point of canvas) after draw second line the plugin will catch the history.
