### ISSUE TITLE
fabric is not defined

### ISSUE THREAD

**Issue by jack-fdrv** [lyzerk/fabric-history#5]
Hi Mate, thank you for your nice plugin.
I try to use it in nuxt js.
When I import your library it says "fabric is not defined"
seems it run history library before fabric. But I am not use how to load it right in nuxt js env for vue js.

Can you please help me?

**Comment by lyzerk** [comment]
Hello,

How did you import fabricjs and fabric-history ?

**Comment by nunure** [comment]
Hello, 

I run in the same issue as you, a simply fix is to create a nuxt plugin:

``` js
import { fabric } from 'fabric'
import 'fabric-history'

export default (_ctx, inject) => {
  inject('fabric', fabric)
}
```

Don't forget to import your plugin in `nuxt.config.js` and you can use fabric with fabric history from anywhere in your app with `this.$fabric`

**Comment by Ocelyn** [comment]
> Hello,
> 
> I run in the same issue as you, a simply fix is to create a nuxt plugin:
> 
> ```js
> import { fabric } from 'fabric'
> import 'fabric-history'
> 
> export default (_ctx, inject) => {
>   inject('fabric', fabric)
> }
> ```
> 
> Don't forget to import your plugin in `nuxt.config.js` and you can use fabric with fabric history from anywhere in your app with `this.$fabric`

Hi nunure, 
I tried your solution but still have the fabric is not defined error,
I have a nuxt project, create a file in plugin folder with your code, but when I add the plugin to my nuxt config I have the error.
Do you have any idea of what I could do ?
Thank you so much

**Comment by nunure** [comment]
How did you import your plugin in `nuxt.config.js` ? 
You need to set `ssr: false` for this kind of plugin

```js
  plugins: [
    { src: '~plugins/fabric', ssr: false } 
  ],
```

**Comment by Ocelyn** [comment]
Thank you so much Nunure it's working! I didn't know this import option!

**Comment by a-y-u-s-h** [comment]
How do you do this in NextJS?

**Comment by viram-ms** [comment]
I am facing same error "fabric is not defined" in next js application.
I have imported :

import { fabric } from "fabric";
import "fabric-history";

**Comment by BossBele** [comment]
`fabricRef` is your canvas:

```
const fabricRef = useRef(null);

const initFabric = useCallback(() => {
    if (typeof fabric !== 'undefined') {
      import('fabric-history')
        .then(() => {
          fabricRef.current = new fabric.Canvas(canvasRef.current);
        })
        .catch(console.error);
    }
  }, [loadFromJSON]);

  const disposeFabric = useCallback(() => {
    if (fabricRef.current && 'dispose' in fabricRef.current) {
      fabricRef.current.dispose();
    }
  }, []);

  useEffect(() => {
    initFabric();
    return () => {
      disposeFabric();
    };
  }, [initFabric, disposeFabric]);
```

**Comment by a-y-u-s-h** [comment]
> 

Too late, I've lost the job now.

**Comment by celioFagundes** [comment]
> ### NextJS Workaound
> `fabricRef` is your canvas:
> 
> ```
> const fabricRef = useRef(null);
> 
> const initFabric = useCallback(() => {
>     if (typeof fabric !== 'undefined') {
>       import('fabric-history')
>         .then(() => {
>           fabricRef.current = new fabric.Canvas(canvasRef.current);
>         })
>         .catch(console.error);
>     }
>   }, []);
> 
>   const disposeFabric = useCallback(() => {
>     if (fabricRef.current && 'dispose' in fabricRef.current) {
>       fabricRef.current.dispose();
>     }
>   }, []);
> 
>   useEffect(() => {
>     initFabric();
>     return () => {
>       disposeFabric();
>     };
>   }, [initFabric, disposeFabric]);
> ```

Could you share more details about this? where is the canvasRef.current coming from at  new fabric.Canvas(canvasRef.current). Also i created the canvas using a state not a ref, you just pass the fabricRef to a <div ref={fabricRef}/>?
