### ISSUE TITLE
Code fails to minify on fabric-js module

### ISSUE THREAD

**Issue by kylekirkby** [lyzerk/fabric-history#6]
Hi @lyzerk,

Thanks for your work on the module! I've been implementing this and noticed you also added support for the `extraProps`! Nice one! However, when I run `yarn build` I get a failed to minify error and it is reporting that the error is occurring on:

```
./node_modules/fabric-history/src/index.js:6
```
Related SO issue:
https://stackoverflow.com/questions/45671597/failed-to-minify-the-code-from-this-file

I'm using webpack with the UglifyJsPlugin. I'm using many other node modules in my app but I'm only getting this issue when including fabric-history. 

Any ideas/help with this would be greatly appreciated!

Cheers!

Kyle

**Comment by lyzerk** [comment]
Hello @kylekirkby,

I have no time this week, I will look the issue at weekend.

Contributions are welcome

**Comment by lyzerk** [comment]
Hello @kylekirkby !

The plugin does not have the minified version. Therefore, Webpack trying to minify it and it causes some problem with prototype extending. Therefore, I just added the minified version of the plugin, when the Webpack will seek for the *.min.js file it wouldn't try to minify it.

Could you update your dependency to 1.2.0 version and test it ?

Thanks.

**Comment by kylekirkby** [comment]
You absolute legend! That makes sense! Let me have a try! 

Best regards,

Kyle

**Comment by kylekirkby** [comment]
I've just tried to push an optimized production build and its falling with the same issue as above :( 
```
✦16 ➜ yarn list | grep "fabric-history"       
├─ fabric-history@1.2.0
```
BR,

Kyle

**Comment by kylekirkby** [comment]
I just tried replacing the index.js with the index.min.js file and I got this error:

```
✦ ➜ yarn build                                         
yarn run v1.21.1
$ node scripts/build.js
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/fabric-history/src/index.js:1:57 
```

Hope that helps!

**Comment by lyzerk** [comment]
Thats interesting, Webpack still trying to minify it. The package json has main property. I have set that into minified version and upgraded into 1.3.0. Can you try it with 1.3.0 version ? 

If it still throw an exception we need to simulate the environment, could you create a sample project that the plugin included and throws exception ?

Thanks !

**Comment by kylekirkby** [comment]
Hi @lyzerk,

Thanks for the help with this! I really appreciate it. I've tested using a basic `npx create-react-app` instance and everything compiles/compresses fine! So I'm putting this down to some bug/issue in an old `webpack 3` build script:

For reference
https://gist.github.com/kylekirkby/045c9404ba6ea0fd71c9298d9a8dc322

The fix for me was to migrate over to a create-react-app instance and use the out-of-the-box build script that they provide!

Best regards,

Kyle
