### ISSUE TITLE
loadfromJSON is maybe asynchronous? 

### ISSUE THREAD

**Issue by morenogiudici** [lyzerk/fabric-history#7]
The script give me some problem that I solve by put false historyProcessing assignment in the callback of loadfromJSON.

I hope this help.

**Comment by morenogiudici** [comment]
Something like that work better for me:
		var self = this;
		this.loadFromJSON(history,function(){
			self.renderAll.bind(canvas);
			self.fire('history:undo');
			self.historyNextState = self._historyNext();
			self.historyProcessing = false;
		});

**Comment by lyzerk** [comment]
I didn't quite understand the problem. Could you explain the problem ?

**Comment by morenogiudici** [comment]
`fabric.Canvas.prototype._historySaveAction = function () {
...
console.log('_historySaveAction');
}
...
fabric.Canvas.prototype.undo = function () {
  this.historyProcessing = true;
  console.log('historyProcessing true');
  const history = this.historyUndo.pop();
  if (history) {
    this.historyRedo.push(this._historyNext());
    this.loadFromJSON(history).renderAll();
    this.fire('history:undo');
  }
  this.historyProcessing = false;
  console.log('historyProcessing false');
}`

The debug sometimes output>
historyProcessing true
historyProcessing false
_historySaveAction
_historySaveAction

**Comment by lyzerk** [comment]
Hello, I think this is a nice point. I will implement it as soon as possible.

**Comment by lyzerk** [comment]
Hello,

Thanks for your feedback, I have fixed it. You can install 1.4.0 version.
