### ISSUE TITLE
how to pass parameters to extraProps

### ISSUE THREAD

**Issue by azeemgujjar** [lyzerk/fabric-history#8]
How to pass values in this.extraProps??
Also how i can manage multiple canvases?

**Comment by azeemgujjar** [comment]
I think reset objection properties as well when i press ctrl+z.. so objects should be move to history with properties and extra properties..
any idea how can i do this? please

**Comment by lyzerk** [comment]
Hello,

You can access extraProps with canvas.extraProps. (e.g canvas.extraProps.push('newProp');) also the plugin working as prototype so each new instance have different history mechanism.
