### ISSUE TITLE
Group deletes

### ISSUE THREAD

**Issue by perryjsteward** [lyzerk/fabric-history#9]
Hi, 

This repo is great and im finding it very useful! I have come across one problem where if i draw a select around multiple objects and then delete those objects i cannot undo that operation.

singular delete appear to work fine for me, but the groups dont.

**use case:** selecting multiple objects, delete those objects and then attempt to undo
**expected outcome:** the group deletion is undone and both object reappear
**actual outcome:**  undoes previous action before deletion

here is how i am deleting objects in Fabricjs:

    const checkforDelete = (e) => {
        if (e.key === 'Backspace' || e.key === 'Delete') {
            const activeObjects = canvas.getActiveObjects();

            // remove objects
            if (activeObjects.length > 0) {
                activeObjects.forEach((object) => {
                    if (!object.isEditing) {
                        canvas.remove(object);
                    }
                });
            }
        }
    };

here is my code for history management:

```
export const History = (canvas) => {
    if (!canvas) return;

    window.addEventListener('keydown', ({ keyCode, ctrlKey, shiftKey }) => {
        // Check Ctrl key is pressed.
        if (!ctrlKey && !keyCode === 91) {
            return;
        }

        // Check pressed button is Z - Ctrl+Z.
        if (keyCode === 90 && !shiftKey) {
            canvas.undo();
        }

        // Check pressed button is Y - Ctrl+Y or Ctrl+Z+Shift
        if (keyCode === 89 || (keyCode === 90 && shiftKey)) {
            canvas.redo();
        }
    });
};
```

**Comment by lyzerk** [comment]
Hi,

Thank you ! Each operation is a history point. Your code will be trigger the history event separately. Therefore, the undo operation is working separately. FabricJS doesn't have 'removeAll' function for your expectation. Maybe we can do a trick about this one but I have to do some research.

**Comment by perryjsteward** [comment]
I think i understand. Would you expect the undo to have to be peformed twice for a case where two objects where deleted in one delete?

**Comment by lyzerk** [comment]
Yes, because you are looping through them. I will try to implement history toggle for such kind of needs. And, it would fit for this situation.

**Comment by lyzerk** [comment]
Hello again,

I have implemented the on/off history functions in 1.6.0. You may use like this,

```javascript
function removeActiveObject() {
    const activeObjects = canvas.getActiveObjects();

    // remove objects
    if (activeObjects.length > 0) {
        canvas.offHistory();

        for (var i = 0; i < activeObjects.length; i++) {
            if (!activeObjects[i].isEditing) {
                canvas.remove(activeObjects[i]);
            }
        }

        canvas.onHistory();
    }
}
```

I think this is what you need !

**Comment by perryjsteward** [comment]
Hi sorry for the late reply. Thanks for looking into this! I think im not following is the onHistory / offHistory an implementation of fabricjs or fabric-history as im getting an error for undefined.

**Comment by perryjsteward** [comment]
Hey this is working great now! thanks very much for looking into this. I think my problem was cached modules. after removing them and reinstalling it all worked fine.
